---
baseURL: "http://localhost:1313"

buildDrafts: true

minify:
  minifyOutput: false

module:
  mounts:
    - source: assets
      target: assets

    - source: static
      target: static

    - source: static/svg/symbols.dev.svg
      target: static/svg/symbols.svg
